language: python

cache: pip

install:
  - pip install ansible

script:
  - ANSIBLE_VAULT_PASSWORD_FILE= ansible-playbook --syntax-check test.yml

before_deploy:
  - openssl aes-256-cbc -K $encrypted_564691d3c8cd_key -iv $encrypted_564691d3c8cd_iv -in vault_password.txt.enc -out vault_password.txt -d
  - mkdir ~/.ssh
  - echo $encrypted_564691d3c8cd_key > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts: opendata02.nine.ch

deploy:
  provider: script
  skip_cleanup: true
  script: ansible-playbook site.yml
  on:
    branch: master
