---
- name: configure SSH authorized keys
  authorized_key: user="{{ ansible_ssh_user }}" key="{{ item }}"
  with_file:
    - fabian.pub
    - hannes.pub
    - oleg.pub
    - ci.pub

- name: add GitHub to known hosts
  known_hosts: host=github.com key="{{ lookup('file', 'github.pub') }}"

- name: create directory for binaries
  file: path=~/bin state=directory

- name: install Composer
  get_url: url=https://getcomposer.org/download/1.10.23/composer.phar dest=~/bin/composer mode=0755 checksum=sha256:2fc3ae370a979602a3bc2c950a38db02e51b4ca2072f7b8e15a518b443b835e7
