---
- name: configure SSH authorized keys
  authorized_key: user="{{ ansible_ssh_user }}" key="{{ item }}"
  with_file:
    - fabian.pub
    - hannes.pub
    - oleg.pub
    - travis.pub

- name: add GitHub to known hosts
  known_hosts: host=github.com key="{{ lookup('file', 'github.pub') }}"

- name: create directory for binaries
  file: path=~/bin state=directory

- name: install Composer
  get_url: url=https://getcomposer.org/download/1.10.6/composer.phar dest=~/bin/composer mode=0755 checksum=sha256:29bdac1bda34d8902b9f9e4f5816de08879b8f3fafad901e4283519cdefbee7b
