---
- name: clone project
  git: repo="https://github.com/OpendataCH/opendata.ch.git" dest="{{ opendata_ch_root }}"
  register: opendata_ch_clone

- name: install Composer dependencies
  composer: command=update prefer_dist=yes working_dir="{{ opendata_ch_root }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.PATH }}"

- name: create wp-config.php
  template: src=wp-config.php.j2 dest="{{ opendata_ch_root }}/wp-config.php"

- name: create .htaccess
  template: src=htaccess.j2 dest="{{ opendata_ch_root }}/.htaccess"

- name: add cron job for Composer updates
  cron: name="composer update opendata.ch" minute=0 hour=16 weekday=0 job="echo \"$(date +'\%Y-\%m-\%d \%T') composer update\" >> {{ ansible_env.HOME }}/composer-update.log; {{ ansible_env.HOME }}/bin/composer update --no-interaction --prefer-dist --no-dev --no-progress --working-dir={{ opendata_ch_root }} >> {{ ansible_env.HOME }}/composer-update.log 2>&1"
