---
- name: clone project
  git: repo="git@github.com:fabian/opendata.ch.git" dest="{{ opendata_ch_root }}"
  register: opendata_ch_clone

- name: install Composer dependencies
  composer: command=install prefer_dist=yes working_dir="{{ opendata_ch_root }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.PATH }}"
