name: Deploy

on:
  push:
    branches: [ master ]

env:
  SSH_HOST_KEY: opendata02.nine.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1U2mdLkqfY5hzBOEvyiFVIif1wXAXOGMHlHhWquH2gYgxalKBOSmQrOXzks8fF7mdW8AR45Z2SbFeSxDZcKWvoIJz1C1Vr48Kt1HDtSq1ZC8w701diK688ErsuqzzBzO8iLycC0dFmFX3tndSAmvKK/8V/AJkhwxjYCW1zZ2PQRlpQK1zue5V/gJn0XWsaTZtAitz7UdenEwBeaPBM+jo3yw7xABdv6tLD/DaSIHU9Sw54OYoJfax+EUx02X9iMQawouQ6kKKhfdDeYqeaRBwCWyotTufQ3ZIpnwiAf0FOFjKn5DMrnQIAE0kTmByDFgjJewp28dAJpW1GHcf4FiR

jobs:
  deploy:

    runs-on: ubuntu-latest

    name: Deployment

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Add vault password
      run: echo "${{ secrets.VAULT_PASSWORD }}" > vault_password.txt

    - name: Run playbook
      run: |
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "${{ env.SSH_HOST_KEY }}" >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
        ansible-playbook site.yml
      env:
        ANSIBLE_FORCE_COLOR: true
